version: '3.7'
services:
  mongodb_container_dishes:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  rabbitmq_container_dishess:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq_data:/var/lib/rabbitmq-dish/

volumes:
  mongodb_data_container:
