version: "3.2"
services:
  mongodb:
    extends: 
      file: ../development/docker-compose.yml
      service: mongodb
  rabbitmq:
    extends:
      file: ../development/docker-compose.yml
      service: rabbitmq
  ingredients:
    build: ../ingredients
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_RABBITMQ_HOST: rabbitmq
  review:
    build: ../review
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_RABBITMQ_HOST: rabbitmq
