name: Deploy
on:
  push:
    branches:
      - master
      - deployment

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deployment.key
          chmod 600 ~/.ssh/deployment.key
          cat >>~/.ssh/config <<END
          Host deployment
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deployment.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Stop the server
        run: ssh deployment 'cd V3B-Food/deployment && docker-compose down'

      - name: Check out the source
        run: ssh deployment "cd V3B-Food && git fetch && git reset --hard origin/master && git checkout $GITHUB_SHA"

      - name: Start the server
        run: ssh deployment 'cd V3B-Food/deployment && docker-compose up -d --build'
