name: Java CI

on: [push]

jobs:
  ingredients:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose -f "development/docker-compose.yml" up -d --build
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven Wrapper
      run: |
        cd ingredients && ./mvnw test -B

  order:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose -f "development/docker-compose.yml" up -d --build
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven Wrapper
      run: |
        cd order && ./mvnw test -B
