name: Java CI

on:
  push:
  workflow_dispatch:

jobs:
  ingredients:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose -f "development/docker-compose.yml" up -d --build
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven Wrapper
      run: |
        cd ingredients && ./mvnw test -B

    - name: Spring boot start
      run: cd ingredients && ./mvnw spring-boot:start

    - uses: matt-ball/newman-action@master
      with:
        collection: ingredients/Food-stock.postman_collection.json
        envVar: '[{ "key": "url", "value": "http://localhost:8082" }]'
    
    - name: Spring boot stop
      run: cd ingredients && ./mvnw spring-boot:stop

  review:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "development/docker-compose.yml" up -d --build
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven Wrapper
        run: |
          cd review && ./mvnw test -B
  dish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "development/docker-compose.yml" up -d --build
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven Wrapper
        run: |
          cd dishes && ./mvnw test -B

  order:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose -f "development/docker-compose.yml" up -d --build
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven Wrapper
      run: |
         cd order && ./mvnw test -B
  customer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start containers
      run: docker-compose -f "development/docker-compose.yml" up -d --build
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven Wrapper
      run: |
        cd customer && ./mvnw test -B
